[versions]
ktx = "1.9.0"

composeBOM = "2023.01.00"
composeActivity = "1.6.1"
composeCoil = "2.2.2"
accompanist = "0.24.11-rc"

hilt = "2.44.2"
androidHiltCompiler = "1.0.0"
hiltNavigationCompose = "1.0.0"
hiltWork = "1.0.0"
javaxInject = "1"

coroutinesCore = "1.6.4"

lifeCycle = "2.5.1"
lifeCycleViewModelKtx = "2.5.1"
lifeCycleRuntimeCompose = "2.6.0-beta01"

navigationCompose = "2.5.3"

retrofit = "2.9.0"
gson = "2.9.0"
loggingInterceptor = "4.10.0"
chucker = "3.5.2"

room = "2.5.0"

junit = "4.13.2"
junitExt = "1.1.5"
coroutinesTest = "1.6.4"
mockitoKotlin = "4.1.0"
mockk = "1.13.5"
runner = "1.4.0"

startupRuntime = "1.1.1"

workRuntimeKtx = "2.8.0"

androidGradlePlugin = "8.0.2"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBOM" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "composeCoil" }
accompanist-webview = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dager-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
android-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidHiltCompiler" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutinesCore" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifeCycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifeCycleViewModelKtx" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifeCycleRuntimeCompose" }

navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gson" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
chucker = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mokito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }

startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupRuntime" }

work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }